# Generated by Django 3.2.9 on 2022-02-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_alter_meet_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
